# -*- coding: utf-8 -*-
"""validation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xu32byROAVMGG8eLzbG4FGAH-cCS5moM
"""

import re
from typing import Dict, Any, Tuple
import database as db

# 1. CLIENT/SERVER INPUT VALIDATION RULES

ORDER_ID_REGEX = re.compile(r"^ORD-\d{6}$")

class InputValidator:
    """Handles client/server-level input sanitization and validation checks."""

    @staticmethod
    def sanitize(text: Any) -> str:
        """Strips leading/trailing whitespace and normalizes empty inputs."""
        return str(text).strip() if text is not None else ""

    @classmethod
    def validate_order_id(cls, order_id: Any) -> Tuple[bool, str, str]:
        """
        Validates an Order ID against formatting requirements.
        Returns: (is_valid: bool, cleaned_id: str, error_message: str)
        """
        cleaned = cls.sanitize(order_id)

        if not cleaned:
            return False, cleaned, "Validation Error: Order ID cannot be empty."

        if not ORDER_ID_REGEX.match(cleaned):
            return False, cleaned, (
                f"Validation Error: Invalid format '{cleaned}'. "
                "Must follow 'ORD-XXXXXX' (e.g., ORD-000001)."
            )

        return True, cleaned, ""

# 2. SAFE SERVICE LAYER (Integration for UI)

class TrackingService:
    """Safe gateway for the UI that intercepts queries with validation."""

    @staticmethod
    def search_shipment(raw_order_id: str) -> Dict[str, Any]:
        """Validates input and queries database without throwing uncaught exceptions."""
        is_valid, cleaned_id, error_msg = InputValidator.validate_order_id(raw_order_id)

        if not is_valid:
            return {
                "success": False,
                "error_type": "INVALID_FORMAT",
                "message": error_msg,
                "data": None
            }

        try:
            # Calls to database functions
            order = db.get_order(cleaned_id)
            if not order:
                return {
                    "success": False,
                    "error_type": "NOT_FOUND",
                    "message": f"Query Error: No shipment found with Order ID '{cleaned_id}'.",
                    "data": None
                }

            history = db.get_tracking_history(cleaned_id)
            return {
                "success": True,
                "error_type": None,
                "message": "Shipment record located successfully.",
                "data": {
                    "order": order,
                    "timeline": history
                }
            }
        except Exception as e:
            return {
                "success": False,
                "error_type": "SYSTEM_EXCEPTION",
                "message": f"Internal database error: {str(e)}",
                "data": None
            }

# 3. QA VERIFICATION & TEST CASES

def run_qa_test_suite():
    """Runs the 3 required use cases per project specification."""
    print("=" * 70)
    print("FASTTRACK COURIER SYSTEM: QA TEST VERIFICATION RUN")
    print("=" * 70)

    # Case 1: Valid Order ID Lookup
    print("\n[TEST CASE 1] Input: 'ORD-000001' (Valid Registered Order)")
    res_1 = TrackingService.search_shipment("ORD-000001")
    print(f"Status: {'PASS' if res_1['success'] else 'FAIL'}")
    print(f"Response Message: {res_1['message']}")
    if res_1["success"]:
        o = res_1["data"]["order"]
        print(f"Details: {o['order_id']} | Route: {o['origin']} -> {o['destination']} | Status: {o['current_status']}")
        print(f"Timeline Events Found: {len(res_1['data']['timeline'])}")

    # Case 2: Invalid Order ID Format / Null Check
    print("\n[TEST CASE 2] Inputs: Invalid Patterns ('BAD-ID', 'ORD-123', '   ')")
    test_inputs = ["BAD-ID", "ORD-123", "   "]
    all_passed_2 = True
    for bad_id in test_inputs:
        res_2 = TrackingService.search_shipment(bad_id)
        passed = (not res_2["success"]) and (res_2["error_type"] == "INVALID_FORMAT")
        if not passed:
            all_passed_2 = False
        print(f" - Input: '{bad_id}' -> Intercepted: {res_2['message']}")
    print(f"Status: {'PASS' if all_passed_2 else 'FAIL'}")

    # Case 3: Non-Existent Order ID Lookup
    print("\n[TEST CASE 3] Input: 'ORD-999999' (Correct Format, Non-Existent ID)")
    res_3 = TrackingService.search_shipment("ORD-999999")
    passed_3 = (not res_3["success"]) and (res_3["error_type"] == "NOT_FOUND")
    print(f"Status: {'PASS' if passed_3 else 'FAIL'}")
    print(f"Response Message: {res_3['message']}")

    print("\n" + "=" * 70)
    print("ALL QA CHECKS COMPLETED")
    print("=" * 70)


if __name__ == "__main__":
    run_qa_test_suite()